### ISSUE TITLE
Upgrade to 3.8 menus

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-gis#7] opened 2019-09-11 22:37 UTC
@ebrelsford We should probably have some consistency with the 3.8. I don't think this is all that important right away but something to consider as we finalize the draft.

**Comment by ebrelsford** [comment] 2019-09-24 03:58
Duplicate of #2

**Closed as completed by ebrelsford** 2019-09-24 03:58 UTC
